# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
min_fastlane_version("2.74.1")

default_platform(:ios)

platform :ios do
  before_all do
    cocoapods
    # cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    run_tests
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number
    build_app(scheme: "Adfed AR") # more options available

    crashlytics(
      api_token: "b32d95b3f21359a6a5c4fa40489be92b625bfc7d",
      build_secret: "ca23970ce5b3f619752fdc0269ba623824cfeb3edf8681905aab8491bdd33076bB"
    )

    upload_to_testflight
    pilot(skip_waiting_for_build_processing:true)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # sync_code_signing(type: "appstore")
    capture_screenshots
    build_app(scheme: "Adfed AR") # more options available
    skip_waiting_for_build_processing
    # frame_screenshots
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

   # slack(
   #   message: "Successfully deployed new App Update."
   # )
  end

  error do |lane, exception|
   # slack(
   #   message: exception.message,
   #   success: false
   # )
  end
end


# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
